### ISSUE TITLE
[BUG] MongoDB container failing to startup

### ISSUE THREAD

**Issue by u6jg1** [typhon-project/typhondl#81]
Issue when running docker-compose up --build:

products_1 | Error saving history file: FileOpenFailed Unable to open() file /home/mongodb/.dbshell: No such file or directory

I think this is what's causing it to cycle and keep trying to run Spring and just failing till it times out.
I've added the full console output too if it helps.

docker-compose version 1.27.4, build 40524192

[console-output.txt](https://github.com/typhon-project/typhondl/files/5567842/console-output.txt)

**Comment by MarieSaphira** [comment]
No that's normal. The error you are having is this:
```
typhon-polystore-service_1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mainController': Invocation of init method failed; nested exception is java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
typhon-polystore-service_1  |   at com.clms.typhonapi.utils.ServiceRegistry.parseDbElement(ServiceRegistry.java:211)
```
Can you please make sure you have the latest image versions (docker-compose pull). I tested your [script](https://github.com/typhon-project/use-cases/tree/gmv-usecase/gmv-usecase/models/m01_space_data_catalogue/space_data_catalogue) and it was working fine.
And since no image is getting built when starting the polystore, you don't need the `--build` option.

**Comment by u6jg1** [comment]
Moving the model to a new eclipse project and regenerating the DL scripts fixed this issue, as it doesn't work with multiple DL scripts in the same project
